"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Detectar el entorno (local o Azure)
# En producción (Azure App Service) configurar la variable de entorno DJANGO_ENV=production
ENVIRONMENT = os.environ.get('DJANGO_ENV', 'local')
IS_PRODUCTION = (ENVIRONMENT == 'production')

# SECURITY WARNING: keep the secret key used in production secret!
# En producción SIEMPRE leer una clave segura desde el entorno
if IS_PRODUCTION:
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
    if not SECRET_KEY:
        raise ValueError('DJANGO_SECRET_KEY must be set in production environment')
else:
    # En desarrollo, usar clave insegura (Django lo avisa automáticamente)
    SECRET_KEY = 'django-insecure-5f5a9+76n-jm(l%eo)r#@^zb3iirkk_)%_$m4ywlrw)b6u!#5_'

# SECURITY WARNING: don't run with debug turned on in production!
if IS_PRODUCTION:
    # En producción SIEMPRE DEBUG=False
    DEBUG = False
else:
    # En desarrollo, usar DEBUG=True para mensajes de error detallados y recarga automática
    DEBUG = True

# Configurar ALLOWED_HOSTS según el entorno
if IS_PRODUCTION:
    # En Azure, aceptar dominios de Azure y cualquier subdominio
    ALLOWED_HOSTS = [
        '*.azurewebsites.net',  # Cualquier app service en Azure
        os.environ.get('DJANGO_ALLOWED_HOST', 'localhost'),  # Host específico si se proporciona
    ]
else:
    # En desarrollo, permitir localhost y 127.0.0.1
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Proyecto
    'compras',
    # API REST
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise debe ir justo después de SecurityMiddleware para que pueda
    # servir archivos estáticos directamente desde el mismo proceso WSGI.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-do'

TIME_ZONE = 'America/Santo_Domingo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# En producción (App Service) Django no sirve estáticos por sí mismo, así que
# recogemos en una carpeta distinta y dejamos que WhiteNoise los sirva.
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Tell Django to use WhiteNoise storage backend so that files are compressed
# and named with hashes for cache busting.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'compras:index'
LOGOUT_REDIRECT_URL = 'login'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}
