"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Detectar el entorno (local o Azure)
# En producción (Azure App Service) configurar la variable de entorno DJANGO_ENV=production
ENVIRONMENT = os.environ.get('DJANGO_ENV', 'local')
IS_PRODUCTION = (ENVIRONMENT == 'production')
WEBSITE_HOSTNAME = os.environ.get('WEBSITE_HOSTNAME')
CUSTOM_ALLOWED_HOST = os.environ.get('DJANGO_ALLOWED_HOST')

# SECURITY WARNING: keep the secret key used in production secret!
# En producción SIEMPRE leer una clave segura desde el entorno
if IS_PRODUCTION:
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
    if not SECRET_KEY:
        raise ValueError('DJANGO_SECRET_KEY must be set in production environment')
else:
    # En desarrollo, usar clave insegura (Django lo avisa automáticamente)
    SECRET_KEY = 'django-insecure-5f5a9+76n-jm(l%eo)r#@^zb3iirkk_)%_$m4ywlrw)b6u!#5_'

# SECURITY WARNING: don't run with debug turned on in production!
if IS_PRODUCTION:
    # En producción SIEMPRE DEBUG=False
    DEBUG = False
else:
    # En desarrollo, usar DEBUG=True para mensajes de error detallados y recarga automática
    DEBUG = True

# Configurar ALLOWED_HOSTS según el entorno
if IS_PRODUCTION:
    # En Azure, aceptar el hostname real del App Service y dominios de Azure.
    ALLOWED_HOSTS = ['.azurewebsites.net']
    if WEBSITE_HOSTNAME:
        ALLOWED_HOSTS.append(WEBSITE_HOSTNAME)
    if CUSTOM_ALLOWED_HOST:
        ALLOWED_HOSTS.append(CUSTOM_ALLOWED_HOST)
else:
    # En desarrollo, permitir localhost y 127.0.0.1
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]', '*']

CSRF_TRUSTED_ORIGINS = []
if IS_PRODUCTION:
    if WEBSITE_HOSTNAME:
        CSRF_TRUSTED_ORIGINS.append(f'https://{WEBSITE_HOSTNAME}')
    if CUSTOM_ALLOWED_HOST:
        if CUSTOM_ALLOWED_HOST.startswith('http://') or CUSTOM_ALLOWED_HOST.startswith('https://'):
            CSRF_TRUSTED_ORIGINS.append(CUSTOM_ALLOWED_HOST)
        else:
            CSRF_TRUSTED_ORIGINS.append(f'https://{CUSTOM_ALLOWED_HOST}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Proyecto
    'compras',
    # API REST
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise debe ir justo después de SecurityMiddleware para que pueda
    # servir archivos estáticos directamente desde el mismo proceso WSGI.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'opencensus.ext.django.middleware.OpencensusMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

APPLICATIONINSIGHTS_CONNECTION_STRING = os.environ.get('APPLICATIONINSIGHTS_CONNECTION_STRING')
if not APPLICATIONINSIGHTS_CONNECTION_STRING:
    instrumentation_key = os.environ.get('APPINSIGHTS_INSTRUMENTATIONKEY')
    if instrumentation_key:
        APPLICATIONINSIGHTS_CONNECTION_STRING = f'InstrumentationKey={instrumentation_key}'

# Application Insights - Instrumentación para telemetría en Azure
OPENCENSUS = {
    'TRACE': {
        'SAMPLER': 'opencensus.trace.samplers.ProbabilitySampler(rate=1.0)',
        'EXPORTER': 'opencensus.ext.azure.trace_exporter.AzureExporter(connection_string=APPLICATIONINSIGHTS_CONNECTION_STRING)',
    },
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if IS_PRODUCTION:
    azure_sql_db = os.environ.get('AZURE_SQL_DB')
    azure_sql_server = os.environ.get('AZURE_SQL_SERVER')
    azure_sql_managed_identity_client_id = os.environ.get('AZURE_SQL_MANAGED_IDENTITY_CLIENT_ID')

    if not azure_sql_db or not azure_sql_server:
        raise ValueError('AZURE_SQL_DB and AZURE_SQL_SERVER must be set in production environment')

    database_config = {
        'ENGINE': 'mssql',
        'NAME': azure_sql_db,
        'HOST': azure_sql_server,
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Authentication=ActiveDirectoryMsi;Encrypt=yes;TrustServerCertificate=no',
            'connection_timeout': 30,
            'connection_retries': 5,
            'connection_retry_backoff_time': 5,
        },
    }

    # Si en el futuro se usa una identidad administrada "user-assigned",
    # Azure SQL requiere enviar el client ID como UID.
    if azure_sql_managed_identity_client_id:
        database_config['USER'] = azure_sql_managed_identity_client_id

    DATABASES = {
        'default': database_config,
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-do'

TIME_ZONE = 'America/Santo_Domingo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# En producción (App Service) Django no sirve estáticos por sí mismo, así que
# recogemos en una carpeta distinta y dejamos que WhiteNoise los sirva.
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Tell Django to use WhiteNoise storage backend so that files are compressed
# and named with hashes for cache busting.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'compras:index'
LOGOUT_REDIRECT_URL = 'login'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Integración con WS Contable
WS_CONTABLE_ENABLED = env_bool('WS_CONTABLE_ENABLED', False)
WS_CONTABLE_BASE_URL = os.environ.get('WS_CONTABLE_BASE_URL', 'http://151.242.194.24').strip()
WS_CONTABLE_TIMEOUT = float(os.environ.get('WS_CONTABLE_TIMEOUT', '10'))
WS_CONTABLE_AUXILIAR_ID = int(os.environ.get('WS_CONTABLE_AUXILIAR_ID', '7'))
WS_CONTABLE_CUENTA_DEBITO_ID = int(os.environ.get('WS_CONTABLE_CUENTA_DEBITO_ID', '2'))
WS_CONTABLE_CUENTA_CREDITO_ID = int(os.environ.get('WS_CONTABLE_CUENTA_CREDITO_ID', '1'))
