# Generated by Django 6.0.3 on 2026-03-10 05:12

import re

from django.db import migrations, models


def normalizar_documentos_proveedor(apps, schema_editor):
    Proveedor = apps.get_model('compras', 'Proveedor')

    for proveedor in Proveedor.objects.all():
        documento = re.sub(r'\D', '', proveedor.cedula_rnc or '')
        proveedor.cedula_rnc = documento[:11]
        proveedor.tipo_documento = 'CED' if len(documento) == 11 else 'RNC'
        proveedor.save(update_fields=['cedula_rnc', 'tipo_documento'])


def revertir_normalizacion_documentos_proveedor(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cantidad_retenida',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad en Hold'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('CED', 'Cédula'), ('RNC', 'RNC')], default='RNC', max_length=3, verbose_name='Tipo de Documento'),
        ),
        migrations.RunPython(
            normalizar_documentos_proveedor,
            reverse_code=revertir_normalizacion_documentos_proveedor,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='existencia',
            field=models.PositiveIntegerField(default=0, verbose_name='Existencia'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('AP', 'Aprobada'), ('CO', 'Completada'), ('RE', 'Rechazada')], default='PE', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cedula_rnc',
            field=models.CharField(max_length=11, unique=True, verbose_name='Cédula / RNC'),
        ),
    ]
