# Generated by Django 6.0.3 on 2026-03-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_articulo_cantidad_retenida_proveedor_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cedula_rnc',
            field=models.CharField(max_length=13, unique=True, verbose_name='Cédula / RNC'),
        ),
    ]
