# Generated by Django 6.0.3 on 2026-03-10 06:10

from decimal import Decimal

from django.db import migrations, models


TIPO_INVENTARIO_GENERAL = 1
CUENTA_CONTABLE_INVENTARIO = '110101'
CUENTA_CONTABLE_CXP = '210101'


def _monto_total_orden(detalles):
    total = Decimal('0')
    for detalle in detalles:
        total += Decimal(detalle.cantidad) * detalle.costo_unitario
    return total


def generar_asientos_historicos(apps, schema_editor):
    OrdenCompra = apps.get_model('compras', 'OrdenCompra')
    OrdenCompraDetalle = apps.get_model('compras', 'OrdenCompraDetalle')
    AsientoContable = apps.get_model('compras', 'AsientoContable')

    ordenes_completadas = OrdenCompra.objects.filter(estado='CO')

    for orden in ordenes_completadas.iterator():
        detalles = OrdenCompraDetalle.objects.filter(orden_id=orden.id)
        monto_total = _monto_total_orden(detalles)

        if monto_total <= 0:
            continue

        codigo_orden = f'OC-{orden.id:05d}'
        fecha_asiento = orden.fecha_orden

        AsientoContable.objects.update_or_create(
            orden_compra_id=orden.id,
            tipo_movimiento='DB',
            defaults={
                'descripcion': f'{codigo_orden} - Compra inventario'[:200],
                'tipo_inventario': TIPO_INVENTARIO_GENERAL,
                'cuenta_contable': CUENTA_CONTABLE_INVENTARIO,
                'fecha': fecha_asiento,
                'monto': monto_total,
                'estado': True,
            },
        )

        AsientoContable.objects.update_or_create(
            orden_compra_id=orden.id,
            tipo_movimiento='CR',
            defaults={
                'descripcion': f'{codigo_orden} - CxP proveedor'[:200],
                'tipo_inventario': TIPO_INVENTARIO_GENERAL,
                'cuenta_contable': CUENTA_CONTABLE_CXP,
                'fecha': fecha_asiento,
                'monto': monto_total,
                'estado': True,
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_proveedor_cedula_rnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='orden_compra',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='asientos_contables',
                to='compras.ordencompra',
                verbose_name='Orden de Compra Relacionada',
            ),
        ),
        migrations.RunPython(generar_asientos_historicos, noop_reverse),
    ]
