# Generated by Django 6.0.3 on 2026-04-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_asientocontable_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='ws_asiento_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID Asiento WS'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='ws_error',
            field=models.TextField(blank=True, default='', verbose_name='Error envío WS'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='ws_estado_envio',
            field=models.CharField(choices=[('PE', 'Pendiente de envío'), ('EN', 'Enviado'), ('ER', 'Error')], default='PE', max_length=2, verbose_name='Estado envío WS'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='ws_fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha envío WS'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cedula_rnc',
            field=models.CharField(max_length=13, unique=True, verbose_name='Documento'),
        ),
    ]
