# Generated by Django 6.0.3 on 2026-04-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_asientocontable_ws_asiento_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContableIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxiliar_id', models.BigIntegerField(verbose_name='ID Auxiliar WS')),
                ('tipo_inventario_id', models.IntegerField(verbose_name='ID Tipo de Inventario')),
                ('cuenta_debito_id', models.BigIntegerField(verbose_name='ID Cuenta Débito WS')),
                ('cuenta_credito_id', models.BigIntegerField(verbose_name='ID Cuenta Crédito WS')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('fecha_asiento', models.DateField(verbose_name='Fecha del Asiento')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('payload_json', models.TextField(blank=True, default='', verbose_name='Payload JSON')),
                ('ws_estado_envio', models.CharField(choices=[('PE', 'Pendiente de envío'), ('EN', 'Enviado'), ('ER', 'Error')], default='PE', max_length=2, verbose_name='Estado envío WS')),
                ('ws_asiento_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID Asiento WS')),
                ('ws_fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha envío WS')),
                ('ws_error', models.TextField(blank=True, default='', verbose_name='Error envío WS')),
                ('asiento_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integraciones_ws_credito', to='compras.asientocontable', verbose_name='Asiento Crédito')),
                ('asiento_debito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integraciones_ws_debito', to='compras.asientocontable', verbose_name='Asiento Débito')),
                ('orden_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integracion_ws', to='compras.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Integración de Asiento Contable',
                'verbose_name_plural': 'Integraciones de Asientos Contables',
                'ordering': ['-id'],
            },
        ),
    ]
