# Generated by Django 6.0.3 on 2026-04-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_asientocontableintegracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('AP', 'Aprobada'), ('CO', 'Completada'), ('RE', 'Rechazada')], db_index=True, default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
